### ISSUE TITLE
A bug here

### ISSUE THREAD

**Issue by shiluotang** [OlivierLD/JavaHard#3]
https://github.com/OlivierLD/JavaHard/blob/ae091781bc1f98c38e20eced704e0c6165ecba8a/core/src/C/jhard.c#L71

According to the JNI Functions (https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html), the third parameter should be a pointer to a valid address for accepting boolean indicator. Use JNI_FALSE may not lead to crash, if it is actually zero.

Dude, I saw your personal site. There are many cool stuffs your have done on sea. Hope you can do more!

> GetStringUTFChars
> 
> const char * GetStringUTFChars(JNIEnv *env, jstring string,
> jboolean *isCopy);
> 
> Returns a pointer to an array of bytes representing the string in modified UTF-8 encoding. This array is valid until it is released by ReleaseStringUTFChars().
> 
> If isCopy is not NULL, then *isCopy is set to JNI_TRUE if a copy is made; or it is set to JNI_FALSE if no copy is made.
> 
> LINKAGE:
> Index 169 in the JNIEnv interface function table.
> PARAMETERS:
> 
> env: the JNI interface pointer.
> 
> string: a Java string object.
> 
> isCopy: a pointer to a boolean.

**Comment by OlivierLD** [comment]
From the doc, as mentioned above:
GetStringUTFChars
const char * GetStringUTFChars(JNIEnv *env, jstring string,
jboolean *isCopy);

Returns a pointer to an array of bytes representing the string in modified UTF-8 encoding. This array is valid until it is released by ReleaseStringUTFChars().

If isCopy is not NULL, then *isCopy is set to JNI_TRUE if a copy is made; or it is set to JNI_FALSE if no copy is made.

And in fact, JNI_FALSE is defined as follow:
pub const JNI_FALSE: jboolean = 0
